LangString addOrReinstall ${LANG_DANISH} "Tilføj/geninstallér komponenter"
LangString alreadyInstalled ${LANG_DANISH} "Allerede installeret"
LangString alreadyInstalledLong ${LANG_DANISH} "${PRODUCTNAME} ${VERSION} er allerede installeret. Vælg, hvad du vil gøre, og klik Næste for at fortsætte."
LangString appRunning ${LANG_DANISH} "{{product_name}} kører! Luk programmet først, og prøv igen."
LangString appRunningOkKill ${LANG_DANISH} "{{product_name}} kører!$\nKlik OK for at lukke det"
LangString chooseMaintenanceOption ${LANG_DANISH} "Vælg den vedligeholdelse, der skal udføres."
LangString choowHowToInstall ${LANG_DANISH} "Vælg, hvordan ${PRODUCTNAME} skal installeres."
LangString createDesktop ${LANG_DANISH} "Opret genvej på skrivebordet"
LangString dontUninstall ${LANG_DANISH} "Afinstallér ikke"
LangString dontUninstallDowngrade ${LANG_DANISH} "Afinstallér ikke (nedgradering uden afinstallation er slået fra i dette installationsprogram)"
LangString failedToKillApp ${LANG_DANISH} "Kunne ikke lukke {{product_name}}. Luk programmet først, og prøv igen"
LangString installingWebview2 ${LANG_DANISH} "Installerer WebView2..."
LangString newerVersionInstalled ${LANG_DANISH} "En nyere version af ${PRODUCTNAME} er allerede installeret! Det anbefales ikke at installere en ældre version. Vil du alligevel, er det bedst at afinstallere den nuværende version først. Vælg, hvad du vil gøre, og klik Næste for at fortsætte."
LangString older ${LANG_DANISH} "ældre"
LangString olderOrUnknownVersionInstalled ${LANG_DANISH} "En $R4 version af ${PRODUCTNAME} er installeret på din computer. Det anbefales at afinstallere den nuværende version, før du installerer. Vælg, hvad du vil gøre, og klik Næste for at fortsætte."
LangString silentDowngrades ${LANG_DANISH} "Nedgradering er slået fra i dette installationsprogram, så den stille installation kan ikke fortsætte. Brug installationsprogrammet med grafisk brugerflade i stedet.$\n"
LangString unableToUninstall ${LANG_DANISH} "Kunne ikke afinstallere!"
LangString uninstallApp ${LANG_DANISH} "Afinstallér ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_DANISH} "Afinstallér før installation"
LangString unknown ${LANG_DANISH} "ukendt"
LangString webview2AbortError ${LANG_DANISH} "WebView2 kunne ikke installeres! Programmet kan ikke køre uden. Prøv at starte installationsprogrammet igen."
LangString webview2DownloadError ${LANG_DANISH} "Fejl: Download af WebView2 mislykkedes - $0"
LangString webview2DownloadSuccess ${LANG_DANISH} "WebView2-installationsfilen blev hentet"
LangString webview2Downloading ${LANG_DANISH} "Henter WebView2-installationsfilen..."
LangString webview2InstallError ${LANG_DANISH} "Fejl: Installation af WebView2 mislykkedes med fejlkode $1"
LangString webview2InstallSuccess ${LANG_DANISH} "WebView2 blev installeret"
LangString deleteAppData ${LANG_DANISH} "Slet programmets data"
